### ISSUE TITLE
Failed to install ckipnlp[classic]

### ISSUE THREAD

**Issue by xiaopi-ouo** [emfomy/ckipnlp#29]
I need to do constituency parsing on Chinese sentences for research.
Following the instructions in README, I run `pip install ckipnlp[classic]` but got error messages:
```
  Downloading ckip-classic-1.2.1.tar.gz (15 kB)                                                                                                                                                     [32/202]
    ERROR: Command errored out with exit status 1:                                                                                                                                                          
     command: /shared_home/r08922129/anaconda3/envs/syntax/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lz9bumwv/ckip-classic_a6bd4cf92dbc4779965dbd862e3b8187/setup
.py'"'"'; __file__='"'"'/tmp/pip-install-lz9bumwv/ckip-classic_a6bd4cf92dbc4779965dbd862e3b8187/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"
'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-jm753tfu
         cwd: /tmp/pip-install-lz9bumwv/ckip-classic_a6bd4cf92dbc4779965dbd862e3b8187/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lz9bumwv/ckip-classic_a6bd4cf92dbc4779965dbd862e3b8187/setup.py", line 22, in <module>
        assert StrictVersion(setuptools.__version__) >= StrictVersion('40.0'), \
      File "/shared_home/r08922129/anaconda3/envs/syntax/lib/python3.7/distutils/version.py", line 40, in __init__
        self.parse(vstring)
      File "/shared_home/r08922129/anaconda3/envs/syntax/lib/python3.7/distutils/version.py", line 137, in parse
        raise ValueError("invalid version number '%s'" % vstring)
    ValueError: invalid version number '52.0.0.post20210125'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/76/d3/4e7abd934536bf23dabbf41ea5153da893b2a76a2cfadf4746fa9698f3ad/ckip-classic-1.2.1.tar.gz#sha256=67617018e2c2c4a35dee80b9f825205a7503865bb45$
bfd437f8e3f0a124a3b7 (from https://pypi.org/simple/ckip-classic/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading ckip-classic-1.2.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /shared_home/r08922129/anaconda3/envs/syntax/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lz9bumwv/ckip-classic_cae0b38a151740bc9c384c1a6364e8a5/setu$
.py'"'"'; __file__='"'"'/tmp/pip-install-lz9bumwv/ckip-classic_cae0b38a151740bc9c384c1a6364e8a5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'$
'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8qt0_a4g
         cwd: /tmp/pip-install-lz9bumwv/ckip-classic_cae0b38a151740bc9c384c1a6364e8a5/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lz9bumwv/ckip-classic_cae0b38a151740bc9c384c1a6364e8a5/setup.py", line 22, in <module>
        assert StrictVersion(setuptools.__version__) >= StrictVersion('40.0'), \
      File "/shared_home/r08922129/anaconda3/envs/syntax/lib/python3.7/distutils/version.py", line 40, in __init__
        self.parse(vstring)
      File "/shared_home/r08922129/anaconda3/envs/syntax/lib/python3.7/distutils/version.py", line 137, in parse
        raise ValueError("invalid version number '%s'" % vstring)
    ValueError: invalid version number '52.0.0.post20210125'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e5/df/c42e352e906fc73619cbc60bfafde2adeab7164dd86de172a25fbb8c7b04/ckip-classic-1.2.0.tar.gz#sha256=93e97c0a0c82d8a63fbcc7d909b46bc412be87225dc$
74886bff57068eaf7c11 (from https://pypi.org/simple/ckip-classic/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading ckip-classic-1.1.2.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /shared_home/r08922129/anaconda3/envs/syntax/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lz9bumwv/ckip-classic_f234e4803640443681e72f5ec9dfe94c/setu$
.py'"'"'; __file__='"'"'/tmp/pip-install-lz9bumwv/ckip-classic_f234e4803640443681e72f5ec9dfe94c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'$
'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1fxjahsn
         cwd: /tmp/pip-install-lz9bumwv/ckip-classic_f234e4803640443681e72f5ec9dfe94c/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lz9bumwv/ckip-classic_f234e4803640443681e72f5ec9dfe94c/setup.py", line 22, in <module>
        assert StrictVersion(setuptools.__version__) >= StrictVersion('40.0'), \
      File "/shared_home/r08922129/anaconda3/envs/syntax/lib/python3.7/distutils/version.py", line 40, in __init__
        self.parse(vstring)
      File "/shared_home/r08922129/anaconda3/envs/syntax/lib/python3.7/distutils/version.py", line 137, in parse
        raise ValueError("invalid version number '%s'" % vstring)
    ValueError: invalid version number '52.0.0.post20210125'

```

Another question is that I have registered an account at http://parser.iis.sinica.edu.tw/v1/reg.exe
but I didn't see the guide in document to use the online parsing system. The api shown in documents doesn't work either. Could anyone show how to use it? Thanks!

**Comment by emfomy** [comment]
It's an issue of CkipClassic. Please refer to ckiplab/ckip-classic#3

**Comment by emfomy** [comment]
> Another question is that I have registered an account at http://parser.iis.sinica.edu.tw/v1/reg.exe
> but I didn't see the guide in document to use the online parsing system. The api shown in documents doesn't work either. Could anyone show how to use it? Thanks!

Set your username and password in environment variables:
```bash
CKIPPARSER_USERNAME=your_username CKIPPARSER_PASSWORD=your_password ./your_code.py
```

**Comment by emfomy** [comment]
> It's an issue of CkipClassic. Please refer to [ckiplab/ckip-classic#3](https://github.com/ckiplab/ckip-classic/issues/3)

The issue is fixed.

**Comment by emfomy** [comment]
> > Another question is that I have registered an account at http://parser.iis.sinica.edu.tw/v1/reg.exe
> > but I didn't see the guide in document to use the online parsing system. The api shown in documents doesn't work either. Could anyone show how to use it? Thanks!
> 
> Set your username and password in environment variables:
> 
> ```shell
> CKIPPARSER_USERNAME=your_username CKIPPARSER_PASSWORD=your_password ./your_code.py
> ```

Updated in v1.0.2. Now you can set these variables using:

```python
pipeline = CkipPipeline(opts={'con_parser': {'username': YOUR_USERNAME, 'password': YOUR_PASSWORD})
```
