### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'TF_CloseSession'

### ISSUE THREAD

**Issue by How-Wang** [emfomy/ckipnlp#31]
When I run 
```python=
pipeline = CkipPipeline(opts={'con_parser': {'username': '***', 'password': '***'}})
......
pipeline.get_conparse(doc)
```
in a .py file
I can see the output result if it runs and prints in the same time.
But when it have run though all the inputs, and it is going to finish the .py file, I will face downward error.
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\ckiptagger\api.py", line 65, in __del__
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\client\session.py", line 765, in close
AttributeError: 'NoneType' object has no attribute 'TF_CloseSession'
Exception ignored in: <function POS.__del__ at 0x0000017E5D348550>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\ckiptagger\api.py", line 185, in __del__
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\client\session.py", line 765, in close
AttributeError: 'NoneType' object has no attribute 'TF_CloseSession'
```
It's worth mentioning that when i run it in ipynb in same environment, it can run without this error message.
Is there any who was faced with this error message before?

[More Detail of this .py file](https://hackmd.io/@EWWf9n9aTCeyDevL1wcQ5g/ByoMap-Hq)

**Comment by emfomy** [comment]
It seems to be an error from [CkipTagger](https://github.com/ckiplab/ckiptagger).
